name: camino_nomad
description: Camino app.
publish_to: "none"
version: 1.1.2+12

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Json serilization
  json_annotation: ^4.8.0
  #other
  url_launcher: ^6.1.10
  google_maps_flutter: ^2.3.0
  flutter_polyline_points: ^1.0.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  share_plus: ^7.0.2
  diacritic: ^0.1.3
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  flutter_native_splash: ^2.3.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  #Json serilization
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  #Other
  flutter_launcher_icons: ^0.13.1

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon-android.png"
  adaptive_icon_background: "assets/icon/icon-android-bg.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/icon-android.png"
  android_12:
    color: "#ffffff"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hotel/
    - assets/images/custom_icons/
    - assets/images/custom_icons/hotel_type/
    - assets/route_database/route_data/
    - assets/route_database/cities/
    - assets/route_database/hotels/

    - assets/route_database/
